In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
# start frozen lake env
env = gym.make("FrozenLake-v0")

In [3]:
# create the Q-table
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size,action_space_size))

In [4]:
# let's see q_table
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [50]:
# initializting Q-learning parameters
num_episodes = 10000 # play the game 10000 times
max_steps_per_episode = 100 # every game just play 100 steps. even not win or lose

learning_rate = 0.1 # we just use the information 10% of each time
discount_rate = 0.99 # what we think about the furture

exploration_rate = 1 # at first we should make exploration
max_exploration_rate = 1 # we can't pass over 1 becourse it's not mean anythihng
min_exploration_rate = 0 # even we get all the information , we should still exploration
exploration_decay_rate = 0.01 # well ,after 100 times we will just use the min I don't know if it is all right

In [51]:
# The next course prove my concern ,exploration decay rate is too big , so it will become less exploration to fast
exploration_decay_rate = 0.001 # This time will make the 1000 episodes to be the min rate

In [52]:
# recorde all the rewards
rewards_all_episodes = []

In [53]:
# Q-learning algorithm
for episode in range(num_episodes): # which means 10000 times game
    # initialize new episode params
    state = env.reset() # Which is define in the episodic game.Every episode is different from others just restart
    done = False # This is the condition given by the env , if it is always false ,every episode will step 100
    reward_current_episode = 0 # initial this episode's reward . It will given by the env and accurate.It is the return for the agent.
    
    # what happened each step:
    for step in range(max_steps_per_episode): # which means 100 steps
        # Exploration-exploitation trade-off this is easy just tell you how to trade off in math and impliment
        exploration_rate_threhold = random.uniform(0,1)
        if exploration_rate_threhold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
                
        # Take new action thank you for env , I think even alphago will use the same expression. env.step
        new_state,reward,done,info = env.step(action)
        # Update Q-table turns out use is easier to understand it.
        q_table[state,action] = q_table[state,action] * (1 - learning_rate) + learning_rate * (reward + discount_rate*np.max(q_table[new_state,:]))
        # Set new state
        state = new_state
        # Add new reward
        reward_current_episode += reward
        
        # game over buddy
        if done == True:
            break 
        
    # Exploration rate decay which means decay after every episode.It looks like the decay is not like linear decay as I thought
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    # Add current episode reward to total rewards list which will see the result
    rewards_all_episodes.append(reward_current_episode)

In [54]:
# results time
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("********Average reword per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count,":",str(sum(r/1000))) # this is mean
    count += 1000

********Average reword per thousand episodes********

1000 : 0.05400000000000004
2000 : 0.20600000000000016
3000 : 0.43300000000000033
4000 : 0.5910000000000004
5000 : 0.6860000000000005
6000 : 0.7350000000000005
7000 : 0.7060000000000005
8000 : 0.7250000000000005
9000 : 0.7590000000000006
10000 : 0.7370000000000005


In [16]:
# Print the updated Q-table
print("\n*****Q-table*****\n")
print(q_table)


*****Q-table*****

[[0.58478982 0.50717513 0.51196459 0.51454536]
 [0.34396766 0.39831647 0.32057776 0.51696018]
 [0.40516535 0.3934736  0.41628588 0.47415028]
 [0.33313982 0.30029327 0.36478482 0.45418402]
 [0.60292345 0.385171   0.43609818 0.41532004]
 [0.         0.         0.         0.        ]
 [0.1553453  0.17421598 0.37486291 0.1572229 ]
 [0.         0.         0.         0.        ]
 [0.39523419 0.35948398 0.34368163 0.64608977]
 [0.46927049 0.71305599 0.44548304 0.44431532]
 [0.7297678  0.39569863 0.32029667 0.33969359]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.43254886 0.61444516 0.81513174 0.51597853]
 [0.73484234 0.90446302 0.76635708 0.80562953]
 [0.         0.         0.         0.        ]]
