In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
# start frozen lake env
env = gym.make("FrozenLake-v0")

In [3]:
# create the Q-table
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size,action_space_size))

In [4]:
# let's see q_table
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
# initializting Q-learning parameters
num_episodes = 10000 # play the game 10000 times
max_steps_per_episode = 100 # every game just play 100 steps. even not win or lose

learning_rate = 0.1 # we just use the information 10% of each time
discount_rate = 0.99 # what we think about the furture

exploration_rate = 1 # at first we should make exploration
max_exploration_rate = 1 # we can't pass over 1 becourse it's not mean anythihng
min_exploration_rate = 0 # even we get all the information , we should still exploration
exploration_decay_rate = 0.01 # well ,after 100 times we will just use the min I don't know if it is all right

In [13]:
# The next course prove my concern ,exploration decay rate is too big , so it will become less exploration to fast
exploration_decay_rate = 0.001 # This time will make the 1000 episodes to be the min rate

In [14]:
# recorde all the rewards
rewards_all_episodes = []

In [15]:
# Q-learning algorithm
for episode in range(num_episodes): # which means 10000 times game
    # initialize new episode params
    state = env.reset() # Which is define in the episodic game.Every episode is different from others just restart
    done = False # This is the condition given by the env , if it is always false ,every episode will step 100
    reward_current_episode = 0 # initial this episode's reward . It will given by the env and accurate.It is the return for the agent.
    
    # what happened each step:
    for step in range(max_steps_per_episode): # which means 100 steps
        # Exploration-exploitation trade-off this is easy just tell you how to trade off in math and impliment
        exploration_rate_threhold = random.uniform(0,1)
        if exploration_rate_threhold > exploration_rate and ~np.all(q_table[state,:]==0):
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
                
        # Take new action thank you for env , I think even alphago will use the same expression. env.step
        new_state,reward,done,info = env.step(action)
        # Update Q-table turns out use is easier to understand it.
        q_table[state,action] = q_table[state,action] * (1 - learning_rate) + learning_rate * (reward + discount_rate*np.max(q_table[new_state,:]))
        # Set new state
        state = new_state
        # Add new reward
        reward_current_episode += reward
        
        # game over buddy
        if done == True:
            break 
        
    # Exploration rate decay which means decay after every episode.It looks like the decay is not like linear decay as I thought
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    # Add current episode reward to total rewards list which will see the result
    rewards_all_episodes.append(reward_current_episode)

In [16]:
# results time
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("********Average reword per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count,":",str(sum(r/1000))) # this is mean
    count += 1000

********Average reword per thousand episodes********

1000 : 0.04900000000000004
2000 : 0.20500000000000015
3000 : 0.45500000000000035
4000 : 0.5820000000000004
5000 : 0.6810000000000005
6000 : 0.7150000000000005
7000 : 0.7310000000000005
8000 : 0.7240000000000005
9000 : 0.7380000000000005
10000 : 0.7350000000000005


In [17]:
# Print the updated Q-table
print("\n*****Q-table*****\n")
print(q_table)


*****Q-table*****

[[0.60361236 0.4524711  0.46237147 0.46208927]
 [0.34552489 0.29314873 0.24995214 0.51691257]
 [0.38937876 0.41606772 0.41399522 0.47082286]
 [0.22832732 0.30357105 0.18446115 0.45179408]
 [0.61887021 0.36360722 0.34889192 0.35433408]
 [0.         0.         0.         0.        ]
 [0.16437308 0.16545203 0.30757001 0.12860073]
 [0.         0.         0.         0.        ]
 [0.45064093 0.3918083  0.45249991 0.66513172]
 [0.50463268 0.7205136  0.42382602 0.36141869]
 [0.69363264 0.35862291 0.2953961  0.27562932]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.53178038 0.51825753 0.75789783 0.43226265]
 [0.71365949 0.85304089 0.70654032 0.71343118]
 [0.         0.         0.         0.        ]]


In [18]:
# Watch our agent play the game according to the Q-table

# Let's play 3 times:
for episode in range(3):
    # initialize new episode params
    state = env.reset()
    done = False
    print("*******EPISODE {} *********\n\n\n".format(episode+1))
    time.sleep(1)
    # show every step
    for step in range(max_steps_per_episode):
        # Show current state of env on screen
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        # Choose action with highest Q-value for currnet state
        action = np.argmax(q_table[state,:])
        # Take new action
        new_state,reward,done,info = env.step(action)
        # game over
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1: #win
                print("*****You reach the goal!**********")
                time.sleep(3)
            else: # lose
                print("*******You fell though a hole!********************")
                time.sleep(3)
                clear_output(wait=True)
            break
        # Set new state

  (Left)
SFFF
FHFH
FFFH
HFFG
*******You fell though a hole!********************
